In [1]:
import numpy as np   # np is the universal alias

print(np.__version__)

2.4.4


In [2]:
import numpy as np
import time

# Python list approach
lst = list(range(1_000_000))
t0 = time.time()
result = [x * 2 for x in lst]
print(f"List:  {(time.time()-t0)*1000:.1f} ms")

# NumPy approach
arr = np.arange(1_000_000)
t0 = time.time()
result = arr * 2
print(f"NumPy: {(time.time()-t0)*1000:.1f} ms")

List:  85.0 ms
NumPy: 21.0 ms


In [4]:
import numpy as np

# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)          # [1 2 3 4 5]
print(a.dtype)    # int64
print(a.shape)    # (5,)
print(a.ndim)     # 1


[1 2 3 4 5]
int64
(5,)
1


In [5]:
# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)    # (2, 3)

(2, 3)


In [6]:
np.zeros((3, 4))        # all zeros  → shape (3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2, 3))         # all ones   → shape (2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((3, 3), 7)      # filled 7   → shape (3,3)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [9]:
np.eye(4)               # identity matrix 4×4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0, 1, 5)   # 5 points in [0,1]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.rand(3, 3)   # uniform random [0,1)

array([[0.74646318, 0.68813892, 0.33237657],
       [0.55654123, 0.05239079, 0.08140987],
       [0.06280062, 0.31097374, 0.10889463]])

In [16]:
a = np.array([1.5, 2.7, 3.9], dtype=np.float32)
b = np.array([1, 0, 1],       dtype=np.bool_)
c = a.astype(np.int64)    # cast float → int (truncates)

print(c.dtype, b.dtype, c)

int64 bool [1 2 3]


In [17]:
a = np.array([10, 20, 30, 40, 50])


In [18]:
a

array([10, 20, 30, 40, 50])

In [19]:
print(a[0])      # → 10   (first element)
print(a[-1])     # → 50   (last element)
print(a[1:4])    # → [20 30 40]
print(a[::2])    # → [10 30 50] every 2nd
print(a[::-1])   # → [50 40 30 20 10] reversed

10
50
[20 30 40]
[10 30 50]
[50 40 30 20 10]


In [20]:
m = np.array([[1,  2,  3],
              [4,  5,  6],
              [7,  8,  9]])

m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
print(m[0, 2])      # → 3   (row 0, col 2)

3


In [22]:
print(m[1])         # → [4 5 6] entire row

[4 5 6]


In [23]:
print(m[:, 1])      # → [2 5 8] entire column

[2 5 8]


In [24]:
print(m[0:2, 1:3]) # → [[2,3],[5,6]] sub-matrix

[[2 3]
 [5 6]]


In [ ]:
scores = np.array([72, 85, 60, 91, 78, 55])


mask = scores >= 75
print(mask)           # boolean array

print(scores[mask])   # filter high scores
print(scores[scores % 2 == 0])  # even only

[False  True False  True  True False]
[85 91 78]
[72 60 78]


In [27]:
a = [1, 2, 3, 4]
b = [10, 20, 30, 40]

print(a + b)    # [11 22 33 44]

[1, 2, 3, 4, 10, 20, 30, 40]


In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)    # [11 22 33 44]

[11 22 33 44]


In [31]:
print(a + b)    # [11 22 33 44]

[11 22 33 44]


In [32]:
print(b - a)    # [9 18 27 36]
print(a * b)    # [10 40 90 160]
print(b / a)    # [10. 10. 10. 10.]
print(a ** 2)  # [1  4  9 16]

[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 1  4  9 16]


In [55]:
data = np.array([[3, 7, 2],
                 [8, 1, 5]])

print(np.sum(data))           # 26 (total)

26


In [56]:
print(np.sum(data, axis=0))  # column sums
print(np.sum(data, axis=1))  # row sums
print(np.mean(data))          # 4.333
print(np.std(data))           # std deviation

[11  8  7]
[12 14]
4.333333333333333
2.5603819159562025


In [58]:
data

array([[3, 7, 2],
       [8, 1, 5]])

In [37]:
print(np.argmax(data))        # index of max

3


In [38]:
import numpy as np
arr = np.array([10, 50, 30, 50, 20])
print(np.argmax(arr)) 
# Output: 1 (Index of the first 50)


1


In [ ]:
a = np.arange(12)        # [0, 1, ..., 11]

b = a.reshape(3, 4)     # 3 rows × 4 cols
c = a.reshape(4 , -1)    # -1 = infer dim → (4,3)

print(b)
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
print(b.ravel())          # flatten, returns view

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
print(b.flatten())        # flatten, returns copy

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a + 10)   # scalar → every element
print(a * 2)    # multiply each

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


In [45]:
data = np.array([[2., 8., 5.],
                 [4., 6., 3.],
                 [6., 4., 7.]])


In [46]:
mean = data.mean(axis=0)


In [47]:
mean

array([4., 6., 5.])

In [48]:
std  = data.std(axis=0)

In [50]:
norm = (data - mean) / std   # broadcasts!

print(norm.mean(axis=0))    # ≈ [0, 0, 0]

[0. 0. 0.]


In [51]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A @ B          # preferred syntax (PEP 465)
D = np.dot(A, B)   # equivalent
print(C)

[[19 22]
 [43 50]]


In [52]:
# Solve: 3x + y = 9,  x + 2y = 8
A = np.array([[3., 1.],
              [1., 2.]])
b = np.array([9., 8.])

x = np.linalg.solve(A, b)
print(x)  # x = 2, y = 3

[2. 3.]


In [53]:
grades = np.array([55, 72, 90, 45, 83])

result = np.where(grades >= 60, 'pass', 'fail')
print(result)

idx = np.where(grades >= 80)
print(grades[idx])   # high scorers

['fail' 'pass' 'pass' 'fail' 'pass']
[90 83]
